version: 2
updates:
  # NuGet dependencies
  - package-ecosystem: "nuget"
    directory: "/dfa/src/API"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
  # npm dependencies - frontend
  - package-ecosystem: "npm"
    directory: "/dfa/src/UI"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"